### ISSUE TITLE
Multiple static file packages

### ISSUE THREAD

**Issue by titpetric** [rakyll/statik#56]
I'd like to produce two (or more) different statik fs's in different import paths. Due to relying on `init()` and no public API from the package, it's impossible to use both filesystems at the same time; concurrent access is also impossible as `fs.Register` is package-scoped.

I'd propose modifying the API:

`fs.New` would take `zipDatas ...string` and fallback on whatever was put in `fs.Register` (backwards compatible),
The generated filesystem package could add `Data() string` for this purpose in addition to keeping init() behaviour.

**Comment by pkieltyka** [comment]
@titpetric here is a fork'd version with the fix.. https://github.com/goware/statik as well as a new -a flag to pass pkg-level variable name to reference the asset. And fs.New() which accept the zipdata string

**Comment by dolmen** [comment]
This request would change this project from a very minimalist solution to a more general one, but less lightweight.

If you need something less minimalist, just fork the project to build something else.

**Comment by dolmen** [comment]
Well, in fact, you can already do that with the existing code. The trick is to call `fs.New()` before another package registers data again. To achieve that, `fs.New()` has to be called at `init` time (in an `init` function or in a package-scoped variable declaration).

Example:
```go
package pkg1

import (
    "github.com/rakyll/statik/fs"
    _ "pkg1/statik"
)

var FS = fs.New()
```
```go
package pkg2

import (
    "github.com/rakyll/statik/fs"
    _ "pkg2/statik"
)

var FS = fs.New()
```
You can now use both `pkg1.FS` and `pkg2.FS`.

Note: this is garanteed to work because the Go language specification [garantees](https://golang.org/ref/spec#Package_initialization) that "Package initialization—variable initialization and the invocation of init functions—happens in a single goroutine, sequentially, one package at a time."

**Comment by titpetric** [comment]
@pkieltyka thanks, i like that you moved away from `init()`. Going to migrate to your fork, eventually :)

Closing this issue as I don't think my PR is a good way forward. Moving away from init() will be a breaking change either way, and it's not up to me.

**Comment by titpetric** [comment]
@pkieltyka p.s. would be nice if you'd generate `statik.go` and not `static.go` by default ;)

**Comment by aitva** [comment]
Hi! I just hit the same problem. I have two directories in two package and I was very surprise to discover that they are on the same Filesystem. I love the minimalism of statik but this was really unexpected.
